---
image: docker:latest
services:
- docker:dind
stages:
- build
- deploy

variables:
  NODE_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/node:$CI_BUILD_REF_NAME
  POSTGRES_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/postgres:$CI_BUILD_REF_NAME

before_script:
  - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY

build to production:
  stage: build
  script:
    - docker build -t $NODE_RELEASE_IMAGE .
    - docker tag $NODE_RELEASE_IMAGE "$CI_REGISTRY_IMAGE/node:latest"
    - docker push $NODE_RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/node:latest"
    - docker build -f Dockerfile.postgres -t $POSTGRES_RELEASE_IMAGE .
    - docker tag $POSTGRES_RELEASE_IMAGE "$CI_REGISTRY_IMAGE/postgres:latest"
    - docker push $POSTGRES_RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/postgres:latest"
  only:
    - /master|develop/
  environment: production
  tags:
    - docker

deploy to production:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment Production --stack polis-prod --service polis-server --new-image $RELEASE_IMAGE --no-finish-upgrade
  only:
    - /master/
  environment: production
  tags:
    - docker

deploy to development:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment Production --stack polis-dev --service polis-server --new-image $RELEASE_IMAGE --no-finish-upgrade
  only:
    - /develop/
  environment: development
  tags:
    - docker
