version: '2'

services:
  postgres:
    container_name: postgres
    image: "postgres:9.6"
    volumes:
      - .:/code
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=polis
      - POSTGRES_PASSWORD=polis
      - POSTGRES_DB=polisdb

  server:
    container_name: polis-server
    build: .
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=polis
      - POSTGRES_PASSWORD=polis
      - POSTGRES_DB=polisdb


