version: '3.1'

services:
  polis-postgres:
    container_name: polis-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - .:/polisServer
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      - USER_PG=polis
      - PASSWORD_PG=polis
      - DB_PG=polisdb

  polis-server:
    container_name: polis-server
    build: .
    volumes:
      - .:/polisServer
    ports:
      - 5000:5000
    depends_on:
      - polis-postgres
    env_file:
      - env/postgres.env
      - env/docker.env
    command: /polisServer/start-dev.sh
